pandas prac files

In [12]:
import pandas as pd
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [19]:
print(df.head())

     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [20]:
print(df.tail())

       0    1    2    3
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

In [17]:
df.shape

(150, 4)

In [21]:
df.columns

RangeIndex(start=0, stop=4, step=1)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [23]:
df.describe()

                0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333
std      0.828066    0.435866    1.765298    0.762238
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

concatenation

In [36]:
#suppose i need to merge two tables. df1 & df2 are two dataframes.we use concatenation  method to merge two tables. we can use concat() function of pandas library to merge two tables. we can specify the axis parameter to specify the direction of concatenation. if axis=0, then the tables will be merged vertically. if axis=1, then the tables will be merged horizontally.

df1 = pd.DataFrame({
  "A" : [1, 2, 3],
  "B" : ["a", "b", "c"],
  "C" : [10, 20, 30]
})

df2 = pd.DataFrame({
  "A" : [4, 5, 6],
  "B" : ["d", "e", "f"],
  "C" : [40, 50, 60]
})

df = pd.concat([df1, df2], ignore_index=True)

In [33]:
df1

   A  B   C
0  1  a  10
1  2  b  20
2  3  c  30

In [34]:
df2

   A  B   C
0  4  d  40
1  5  e  50
2  6  f  60

In [37]:
df

   A  B   C
0  1  a  10
1  2  b  20
2  3  c  30
3  4  d  40
4  5  e  50
5  6  f  60

merged,joins

In [41]:
df1 = pd.DataFrame({
  "Key" : ['k0', 'k1', 'k2'],
  "A" : ['A0', 'A1', 'A2'],
  "B" : ['B0', 'B1', 'B2']
})

In [57]:
df2 = pd.DataFrame({
  "Key" : ['k1', 'k2', 'k3'],
  "C" : ['C0', 'C1', 'C2'],
  "D" : ['D0', 'D1', 'D2']
})

In [66]:
df = pd.merge(df1, df2,how = 'inner', left_on='Key',right_on='Key')

In [67]:
df

  Key   A   B   C   D
0  k1  A1  B1  C0  D0
1  k2  A2  B2  C1  D1

In [68]:
df = pd.merge(df1, df2,how = 'left', left_on='Key',right_on='Key')
df

  Key   A   B    C    D
0  k0  A0  B0  NaN  NaN
1  k1  A1  B1   C0   D0
2  k2  A2  B2   C1   D1

In [69]:
df = pd.merge(df1, df2,how = 'right', left_on='Key',right_on='Key')
df

  Key    A    B   C   D
0  k1   A1   B1  C0  D0
1  k2   A2   B2  C1  D1
2  k3  NaN  NaN  C2  D2

In [70]:
df = pd.merge(df1, df2,how = 'outer', left_on='Key',right_on='Key')
df

  Key    A    B    C    D
0  k0   A0   B0  NaN  NaN
1  k1   A1   B1   C0   D0
2  k2   A2   B2   C1   D1
3  k3  NaN  NaN   C2   D2